version: '3.7'

x-volumes: &default-volumes
  volumes:
    - ./dist:/app/dist
    - ./js:/app/js
    - ./scss:/app/scss
    - ./webpack.config.js:/app/webpack.config.js
    - ./babel.config.js:/app/babel.config.js

services:
  build:
    build: .
    image: libguides-styles
    command: yarn build:prod
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    # <<: *default-volumes
  
  watch:
    build: .
    image: libguides-styles
    command: yarn build:dev:watch
    <<: *default-volumes

  dev:
    build:
      context: ./test
      dockerfile: Dockerfile
    image: libguides-styles-nginx
    ports:
      - "8080:8080"
    depends_on:
      - watch
    <<: *default-volumes
    