machine-defaults: &machine-defaults
  machine:
    image: ubuntu-2204:current
  working_directory: ~/app

aws_env: &aws_env
  run:
    name: Export AWS Dev env vars
    command: |
      echo 'export AWS_ACCESS_KEY_ID=${WEB_CDN_AWS_ACCESS_KEY_ID}' >> $BASH_ENV
      echo 'export AWS_SECRET_ACCESS_KEY=${WEB_CDN_AWS_SECRET_ACCESS_KEY}' >> $BASH_ENV

# Note that `aws s3 sync ... --exact-timestamps` only works for downloads from S3,
# not uploads: https://github.com/aws/aws-cli/issues/4460.  The only safe way
# to update is to upload absolutely everything using `cp` and then deleting
# removed files using `sync --delete`.  There are many other open GitHub issues
# related to this behavior.  Here's another: https://github.com/aws/aws-cli/issues/3273.
aws-sync-s3: &aws-sync-s3
  run:
    name: Deploy to S3
    command: |
      aws s3 cp --recursive dist ${S3_URI}/libguides && \
      aws s3 sync --delete dist ${S3_URI}/libguides

webpack_build: &webpack_build
  run:
    name: Webpack
    command: |
      NODE_ENV=${NODE_ENV} docker compose run build

webpack_copy: &webpack_copy
  run:
    name: Copy webpack build
    command: |
      docker cp $(docker ps -a -q --filter name=build):/app/dist/ .

version: 2.1
jobs:
  deploy-dev:
    <<: *machine-defaults
    steps:
      - checkout
      - run:
          name: Export Dev environment
          command: |
            echo 'export NODE_ENV=production' >> $BASH_ENV
      - *aws_env
      - *webpack_build
      - *webpack_copy
      - *aws-sync-s3
      - store_artifacts:
          path: dist

  deploy-prod:
    <<: *machine-defaults
    steps:
      - checkout
      - run:
          name: Export Dev environment
          command: |
            echo 'export NODE_ENV=production' >> $BASH_ENV
      - *aws_env
      - *webpack_build
      - *webpack_copy
      - *aws-sync-s3
      - store_artifacts:
          path: dist

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - deploy-dev:
          context: web-cdn-aws-nyulitsdev
          filters:
            branches:
              ignore:
                - master
      - deploy-prod:
          context: web-cdn-aws-nyulits
          filters:
            branches:
              only: master
